# How to build & push image
# run script `yarn build:dev`
# run script `docker build -f Dockerfile.dev --platform linux/amd64 -t registry.quadrakaryasantosa.com/spix-admin:v0.2 .`
# run script `docker push registry.quadrakaryasantosa.com/spix-admin:v0.2`

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY /build /usr/share/nginx/html
ENTRYPOINT ["nginx", "-g", "daemon off;"]